export const work = [
    {
        type: "2020 / now  -  ICCS-NTUA | Athens Greece",
        tasks: [
            [
                `Environmental App | European “R2D2”`,
                `Contracted by ICCS as standalone Full stack Developer to design and develop "R2D2" environmental events repository app and infrastructure. Deliverable is a part of multi European endeavour that roots and founded by greater movement “Horizon 2020”. The project is still in active development.`
            ],
            [
                `Electrical Units Management | “Electro”`,
                `Contracted by operator in the field of "Facilities Climate" installations as standalone Full Stack Developer to design and develop "Electro" equipment management  -  maintenance solution application in the Google Cloud`
            ],
            [
                `2 Energy Apps | European “Synergies"`,
                `Contracted by ICCS as standalone Full stack Developer to design and develop "Synergies" – “Synergy” next level. The project consists of 2 energy apps and portable infrastructure was a part of multi European big-data project ‘Synergies” that comes as a continuity of v.1 "Synergy" project that roots and founded by greater movement “Horizon 2020”. Project customers are major official energy suppliers across Europe`
            ],
            [
                `2 Energy Apps | European - Indian "Re-Empowered"`,
                `Contracted as standalone Full Stack Developer to design and develop 2 energy apps, parts of European - Indian endeavor in the field of Renewable energy, labeled "EcoEms" rooted and empowered by the greater movement “Re-empowered”.The scope of the project was to structure and visualize the overall energy consumption generated by conventional units and eventually use input for administrators to perform simulations so that renewable empowered energy could find and claim its effective margin on the daily demand. Technically the workload dealt with design and implement the infrastructure and 2 web applications for the Greek and Denmark counterparts.`
            ],
            [
                `E-Shop | “Marine Service Parts"`,
                `Contracted by merchandiser in the field of ‘Marine equipment  -  services” as standalone Full Stack Developer to design and develop "Marine Service Parts" maintenance and shopping solution`
            ],
            [
                `2 Energy Apps | European “Synergy"`,
                `Contracted as standalone Full stack Developer to design and develop 2 energy apps, parts of multi European big-data project ‘Synergy” that roots and founded by greater movement “Horizon 2020”. Project customers are major national suppliers across Europe. Scopes of the project are to build infrastructures for the Greek domains that host the apps, communicate and exchange data with the remote core platform and provide analytics and chart visualizations in a way to enhance the customers understanding and tendencies of extensive, collaborative amounts of data.`
            ],
            [
                `Energy App | Official Distributor “Hybrid"`,
                `Contracted as standalone Full stack Developer to design and develop energy management application for the national energy supplier and official subsidiaries distributed across islands. Core scopes of the project: Power Production  -  Load  -  Availability, Technical status of units and ultimately alignment with the official Schedule announced by the national supplier on daily basis. The project consists of several policy restrictions applied at all levels and impose strict time submissions compliance and algorithmic data dependencies. Communication amongst all members addressed within the app with Notifications and Message exchanges. Dockerized infrastructure was installed remotely to national supplier premises at project completion`
            ]
        ]
    },
    {
        type: '2017 / 2020 RATEPARITY  -  COSMORES  | Piraeus Greece',
        tasks: [
            [
                `Booking Conversion Widgets | Rateparity`,
                `Employed as in-house standalone Frontend Developer to build a suite of customizable UI widgets and respective backend configuration application consuming data from remote source Design and develop the app's Installer that can be used on affiliate sites with a single HTML “Head”entry. Design and develop decoupled SPA widgets, that reside on their own domains and can be launched by installer on demand. Publish 5 distinct widget types, with 4 viewport layouts for each, to accommodate diversity of screen displays. Create a React 16.4 application based on a helper theme with some main group activities`
            ],
            [
                `Booking Engine (Hospitality) | Cosmores`,
                `Employed standalone Fullstack Developer to leverage the security, extend and maintain the company's products, refine the lifecycle all the way from development to production. Leverage the security of login by blocking the front entrance and allow only recognizable devices to enter. The activity uses expirable tokens that are only accepted for limited amount of time, and provide respective messages to users for guidance. Leverage the encryption - decryption procedures for all sensitive data in the DB, which led to more than 1M rows update Build common and explicit PHP helper structures to make development lifecycle natively simple and secure. Build a configurable, vanilla Javascript widget for displaying best price of an affiliate hotels and the respective CORS api for consumption`
            ],
        ]
    },
    {
        type: `2016 / 2017  -  ECEP TECHNOLOGIES | London England (remote)`,
        tasks: [
            [
                `Web Warehouse Inventory`,
                `Contracted standalone Full Stack Developer to design and build the company's warehouse inventory using a contemporary tools, discussing with the English entrepreneur on daily basis. Use the Laravel MVC 5.1 Framework to as a robust and secure foundation to build the application and a REST-like API. Design and build an efficient DB system by analyzing and evaluating legacy spreadsheet procedures for more than 500K distinct barcodes`
            ]
        ],
    },
    {
        type: `2015 / 2016 -  SEECAGO | Florida USA (remote)`,
        tasks: [
            [
                `Noblelinx CRM Project`,
                `Contracted as remote standalone Full Stack Developer to follow American coordinator towards extending Noblelinx commercial CRM system, build with legacy PHP constructs. Design root 'User' class, to provide essential features and resources to derived child classes. Set up synchronization between local Calendar libraries and MS Outlook, through Exchange Web Services (EWS), for Calendar Events and User Tasks. Develop Chart-based, time-ranged filtered, auditing for Employees  -  Managers  -  Directors performance. Enforce 90-Days, token-generated with expiry limitation, password restriction for all users`
            ]
        ],
    },
    {
        type: '2014 / 2015 -  INTERACTIVE DATA | Frankfurt Germany (remote)',
        tasks: [
            [
                `Commerzbank "Infobroker" Multinational Project`,
                `Member of Agile-maintained developers group, my key assignment was to design and develop Front-end solutions after translating documented specifications, strictly dictated by customer. Provide Ticketing solution services`
            ]
        ],
    },
    {
        type: '2012 / 2014  -  FREELANCE WEB DEVELOPER',
        tasks: [
            [
                `Interior Design & Materials | Merchandiser Elgreg`,
                'Develop web applications qualified exclusively over latest web standards'
            ]
        ],
    },
    {
        type: '2001 / 2011  -  SANOFI AVENTIS S.A | Athens Greece',
        tasks: [
            [
                `HSE & HR Data Housekeeping and New Media Support (06'-11')`,
                `Design and maintain MS Access software, helper Applications for data housekeeping of ‘HSE Department’ branch of HR Department`
            ],
            [
                "Messenger (01'-06')",
                "Liable for performing the transactions and communications of the Enterprise with the public and private sector services"
            ]
        ],
    }
]

export const study = [
    {
        type: "2009 / 2012  -  BSc (Hons) in Internet Engineering & Web Management",
        tasks: [
            "University of Greenwich in association with New York College Athens, Greece. First Class Honours Degree: Graduated first in class with distinction"
        ]
    },
    {
        type: "2008 / 2009  -  Certificate in Web design and Development",
        tasks: [
            "Intergraphics’ Vocational Training, Athens, Greece"
        ]
    },
    {
        type: "2005 / 2006  -  Certificate in Graphical Design for digital and Printable Mediums",
        tasks: [
            "AKMI’ Vocational Training, Athens, Greece"
        ]
    },
    {
        type: "2001 / 2003  -  Certificate in Visual Design and 3D-Animation",
        tasks: [
            "AKMI’ Vocational Training, Athens, Greece"
        ]
    },
]

export const tool = [
    {
        type: "Experience",
        tasks: [
            `Node.js, Svelte, Nest.js, React.js, Next.js, ES6+, Web Components, PHP, MySQL, HTML5, CSS3, SCSS, Bootstrap, EWS, XML, XSLT, Docker, Docker-Compose,  Webpack, Vite, Typescript, Jest, Git, SVN, Nginx, Apache, Virtualbox, Linux-Terminal, Keycloak, Prometheus, Grafana, RabbitMQ`
        ]
    },
]

export const os = [
    {
        type: "Environment",
        tasks: [
            "Ubuntu, Fedora, Centos, Windows"
        ]
    },
]
export const ide = [
    {
        type: "Development",
        tasks: [
            "PHPStorm, Eclipse, Notepad++"
        ]
    },
    {
        type: "Visuals",
        tasks: [
            "Adobe Master Suite, MS Access, MS Visio"
        ]
    },
]
export const lang = [
    {
        type: "English",
        tasks: [
            "Studies by English University, Cambridge Lower Certificate"
        ]
    },
    {
        type: "Greek",
        tasks: [
            "Native speaker"
        ]
    },
]